version: '3.9'

services:
  postgres-user-service:
    image: postgres:15
    container_name: postgres_user_service
    environment:
      POSTGRES_USER: movietime_user
      POSTGRES_PASSWORD: movietime_pass
      POSTGRES_DB: user_service_db
    ports:
      - "5432:5432"
    volumes:
      - user_service_db_data:/var/lib/postgresql/data
    networks:
      - movietime-network

networks:
  movietime-network:

volumes:
  user_service_db_data: